### ISSUE TITLE
E: Unable to locate package log2ram

### ISSUE THREAD

**Issue by onlineapps-cloud** [azlux/log2ram#220] opened 2024-02-27 22:06 UTC
hi, i tried to install log2ram on proxmox 8 (debian 11 bookworm) but i get error:
```
echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bookworm main" | tee /etc/apt/sources.li
st.d/azlux.list
wget -O /usr/share/keyrings/azlux-archive-keyring.gpg  https://azlux.fr/repo.gpg
apt update
apt install log2ram
deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bookworm main
--2024-02-28 00:02:37--  https://azlux.fr/repo.gpg
Resolving azlux.fr (azlux.fr)... 0.0.0.0, ::
Connecting to azlux.fr (azlux.fr)|0.0.0.0|:443... failed: Connection refused.
Connecting to azlux.fr (azlux.fr)|::|:443... failed: Connection refused.
Hit:1 http://ftp.ro.debian.org/debian bookworm InRelease
Hit:2 http://ftp.ro.debian.org/debian bookworm-updates InRelease                
Ign:3 http://packages.azlux.fr/debian bookworm InRelease                        
Hit:4 http://security.debian.org bookworm-security InRelease                    
Hit:5 http://download.proxmox.com/debian/pve bookworm InRelease                 
Ign:3 http://packages.azlux.fr/debian bookworm InRelease
Ign:3 http://packages.azlux.fr/debian bookworm InRelease
Err:3 http://packages.azlux.fr/debian bookworm InRelease
  Could not connect to packages.azlux.fr:80 (0.0.0.0). - connect (111: Connection refused) Could not connect to packages.azlux.fr:80 (::). - connect (111: Connection refused)
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
All packages are up to date.
W: Failed to fetch http://packages.azlux.fr/debian/dists/bookworm/InRelease  Could not connect to packages.azlux.fr:80 (0.0.0.0). - connect (111: Connection refused) Could not connect to packages.azlux.fr:80 (::). - connect (111: Connection refused)
W: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package log2ram
```

**Comment by JakobLichterfeld** [comment] 2024-03-23 14:46
duplicate of #221

**Closed** 2024-03-24 21:29 UTC
